name: Pipeline Image

on:
    # Trigger on all pull requests.
    pull_request:
    # Trigger on all pushes to main.
    push:
      branches:
        - main

jobs:
    prepare:
        runs-on: ubuntu-latest
        steps:
            - id: repository_name
              run: |
                lowercase_repo_name=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
                echo "lowercase_repo_name=${lowercase_repo_name}" >> $GITHUB_OUTPUT
        outputs:
            lowercase_repo_name: ${{ steps.repository_name.outputs.lowercase_repo_name }}

    build-etl-pipeline:
        runs-on: ubuntu-latest
        needs: prepare
        steps:
            - uses: actions/checkout@v3
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build ${{ needs.prepare.outputs.lowercase_repo_name }}-etl-pipeline and push to GitHub Container Registry
              run: |
                docker build --platform linux/amd64 -t ghcr.io/zenysis/${{ needs.prepare.outputs.lowercase_repo_name }}-etl-pipeline:${{ github.head_ref || github.ref_name }} -f docker/pipeline/Dockerfile --cache-from ghcr.io/zenysis/${{ needs.prepare.outputs.lowercase_repo_name }}-etl-pipeline:main,ghcr.io/zenysis/${{ needs.prepare.outputs.lowercase_repo_name }}-etl-pipeline:${{ github.head_ref || github.ref_name }} --build-arg BUILDKIT_INLINE_CACHE=1 .
                docker push ghcr.io/zenysis/${{ needs.prepare.outputs.lowercase_repo_name }}-etl-pipeline:${{ github.head_ref || github.ref_name }}
            - name: Login to Docker Hub
              if: ${{ github.head_ref == 'main' }}
              uses: docker/login-action@v2
              with:
                registry: docker.io
                username: ${{ secrets.ZENGENEERING_DOCKER_USERNAME }}
                password: ${{ secrets.ZENGENEERING_DOCKER_PASSWORD }}
            - name: Push to Docker Hub
              if: ${{ github.head_ref == 'main' }}
              run: |
                docker tag ghcr.io/zenysis/${{ needs.prepare.outputs.lowercase_repo_name }}-etl-pipeline:${{ github.head_ref || github.ref_name }} zengineering/${{ needs.prepare.outputs.lowercase_repo_name }}-etl-pipeline:latest
                docker push zengineering/${{ needs.prepare.outputs.lowercase_repo_name }}-etl-pipeline:latest
